"""Add board_post_number to posts

Revision ID: 15347b060ab9
Revises: 5be677403ab6
Create Date: 2024-05-23 02:59:10.380921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15347b060ab9'
down_revision: Union[str, None] = '5be677403ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('board_post_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'board_post_number')
    # ### end Alembic commands ###
