"""Add tags_relationship to posts

Revision ID: 84c37fab6755
Revises: 412a2bfa0569
Create Date: 2024-05-22 01:48:27.945035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c37fab6755'
down_revision: Union[str, None] = '412a2bfa0569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
